# Generated by Django 5.0.3 on 2024-04-02 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='facebook',
            new_name='github',
        ),
    ]
