# Generated by Django 5.0.3 on 2024-03-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
        migrations.AddField(
            model_name='course',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
