# Generated by Django 5.0.3 on 2024-03-31 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_category_course_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Write Tag Name', max_length=50, null=True, unique=True, verbose_name='Tag Name')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
