# Generated by Django 5.0.3 on 2024-03-31 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='courses.tag'),
        ),
    ]
